spring:
  datasource:
    username: root
    password: 12345
    url: jdbc:mysql://localhost:3306/domain_app
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: bupt.dawsonlee1790.domaindimysql.entity